/*
Copyright 2018 interma.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/interma/programming-k8s/pkg/apis/stats/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCpus implements CpuInterface
type FakeCpus struct {
	Fake *FakeStatV1alpha1
	ns   string
}

var cpusResource = schema.GroupVersionResource{Group: "stat.example.org", Version: "v1alpha1", Resource: "cpus"}

var cpusKind = schema.GroupVersionKind{Group: "stat.example.org", Version: "v1alpha1", Kind: "Cpu"}

// Get takes name of the cpu, and returns the corresponding cpu object, and an error if there is any.
func (c *FakeCpus) Get(name string, options v1.GetOptions) (result *v1alpha1.Cpu, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(cpusResource, c.ns, name), &v1alpha1.Cpu{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Cpu), err
}

// List takes label and field selectors, and returns the list of Cpus that match those selectors.
func (c *FakeCpus) List(opts v1.ListOptions) (result *v1alpha1.CpuList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(cpusResource, cpusKind, c.ns, opts), &v1alpha1.CpuList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CpuList{}
	for _, item := range obj.(*v1alpha1.CpuList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested cpus.
func (c *FakeCpus) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(cpusResource, c.ns, opts))

}

// Create takes the representation of a cpu and creates it.  Returns the server's representation of the cpu, and an error, if there is any.
func (c *FakeCpus) Create(cpu *v1alpha1.Cpu) (result *v1alpha1.Cpu, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(cpusResource, c.ns, cpu), &v1alpha1.Cpu{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Cpu), err
}

// Update takes the representation of a cpu and updates it. Returns the server's representation of the cpu, and an error, if there is any.
func (c *FakeCpus) Update(cpu *v1alpha1.Cpu) (result *v1alpha1.Cpu, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(cpusResource, c.ns, cpu), &v1alpha1.Cpu{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Cpu), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCpus) UpdateStatus(cpu *v1alpha1.Cpu) (*v1alpha1.Cpu, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(cpusResource, "status", c.ns, cpu), &v1alpha1.Cpu{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Cpu), err
}

// Delete takes name of the cpu and deletes it. Returns an error if one occurs.
func (c *FakeCpus) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(cpusResource, c.ns, name), &v1alpha1.Cpu{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCpus) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(cpusResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.CpuList{})
	return err
}

// Patch applies the patch and returns the patched cpu.
func (c *FakeCpus) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Cpu, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(cpusResource, c.ns, name, data, subresources...), &v1alpha1.Cpu{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Cpu), err
}
