/*
Copyright 2018 interma.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/interma/programming-k8s/pkg/apis/stats/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePodStatses implements PodStatsInterface
type FakePodStatses struct {
	Fake *FakeStatV1alpha1
	ns   string
}

var podstatsesResource = schema.GroupVersionResource{Group: "stat.example.org", Version: "v1alpha1", Resource: "podstatses"}

var podstatsesKind = schema.GroupVersionKind{Group: "stat.example.org", Version: "v1alpha1", Kind: "PodStats"}

// Get takes name of the podStats, and returns the corresponding podStats object, and an error if there is any.
func (c *FakePodStatses) Get(name string, options v1.GetOptions) (result *v1alpha1.PodStats, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(podstatsesResource, c.ns, name), &v1alpha1.PodStats{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PodStats), err
}

// List takes label and field selectors, and returns the list of PodStatses that match those selectors.
func (c *FakePodStatses) List(opts v1.ListOptions) (result *v1alpha1.PodStatsList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(podstatsesResource, podstatsesKind, c.ns, opts), &v1alpha1.PodStatsList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PodStatsList{}
	for _, item := range obj.(*v1alpha1.PodStatsList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested podStatses.
func (c *FakePodStatses) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(podstatsesResource, c.ns, opts))

}

// Create takes the representation of a podStats and creates it.  Returns the server's representation of the podStats, and an error, if there is any.
func (c *FakePodStatses) Create(podStats *v1alpha1.PodStats) (result *v1alpha1.PodStats, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(podstatsesResource, c.ns, podStats), &v1alpha1.PodStats{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PodStats), err
}

// Update takes the representation of a podStats and updates it. Returns the server's representation of the podStats, and an error, if there is any.
func (c *FakePodStatses) Update(podStats *v1alpha1.PodStats) (result *v1alpha1.PodStats, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(podstatsesResource, c.ns, podStats), &v1alpha1.PodStats{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PodStats), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePodStatses) UpdateStatus(podStats *v1alpha1.PodStats) (*v1alpha1.PodStats, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(podstatsesResource, "status", c.ns, podStats), &v1alpha1.PodStats{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PodStats), err
}

// Delete takes name of the podStats and deletes it. Returns an error if one occurs.
func (c *FakePodStatses) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(podstatsesResource, c.ns, name), &v1alpha1.PodStats{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePodStatses) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(podstatsesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.PodStatsList{})
	return err
}

// Patch applies the patch and returns the patched podStats.
func (c *FakePodStatses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.PodStats, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(podstatsesResource, c.ns, name, data, subresources...), &v1alpha1.PodStats{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PodStats), err
}
