/*
Copyright 2018 interma.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	stats_v1alpha1 "github.com/interma/programming-k8s/pkg/apis/stats/v1alpha1"
	versioned "github.com/interma/programming-k8s/pkg/client/clientset/versioned"
	internalinterfaces "github.com/interma/programming-k8s/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/interma/programming-k8s/pkg/client/listers/stats/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PodStatsInformer provides access to a shared informer and lister for
// PodStatses.
type PodStatsInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.PodStatsLister
}

type podStatsInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPodStatsInformer constructs a new informer for PodStats type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPodStatsInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPodStatsInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPodStatsInformer constructs a new informer for PodStats type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPodStatsInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.StatV1alpha1().PodStatses(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.StatV1alpha1().PodStatses(namespace).Watch(options)
			},
		},
		&stats_v1alpha1.PodStats{},
		resyncPeriod,
		indexers,
	)
}

func (f *podStatsInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPodStatsInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *podStatsInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&stats_v1alpha1.PodStats{}, f.defaultInformer)
}

func (f *podStatsInformer) Lister() v1alpha1.PodStatsLister {
	return v1alpha1.NewPodStatsLister(f.Informer().GetIndexer())
}
