/*
Copyright 2018 interma.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/interma/programming-k8s/pkg/apis/stats/v1alpha1"
	scheme "github.com/interma/programming-k8s/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PodStatsesGetter has a method to return a PodStatsInterface.
// A group's client should implement this interface.
type PodStatsesGetter interface {
	PodStatses(namespace string) PodStatsInterface
}

// PodStatsInterface has methods to work with PodStats resources.
type PodStatsInterface interface {
	Create(*v1alpha1.PodStats) (*v1alpha1.PodStats, error)
	Update(*v1alpha1.PodStats) (*v1alpha1.PodStats, error)
	UpdateStatus(*v1alpha1.PodStats) (*v1alpha1.PodStats, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.PodStats, error)
	List(opts v1.ListOptions) (*v1alpha1.PodStatsList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.PodStats, err error)
	PodStatsExpansion
}

// podStatses implements PodStatsInterface
type podStatses struct {
	client rest.Interface
	ns     string
}

// newPodStatses returns a PodStatses
func newPodStatses(c *StatV1alpha1Client, namespace string) *podStatses {
	return &podStatses{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the podStats, and returns the corresponding podStats object, and an error if there is any.
func (c *podStatses) Get(name string, options v1.GetOptions) (result *v1alpha1.PodStats, err error) {
	result = &v1alpha1.PodStats{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("podstatses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of PodStatses that match those selectors.
func (c *podStatses) List(opts v1.ListOptions) (result *v1alpha1.PodStatsList, err error) {
	result = &v1alpha1.PodStatsList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("podstatses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested podStatses.
func (c *podStatses) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("podstatses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a podStats and creates it.  Returns the server's representation of the podStats, and an error, if there is any.
func (c *podStatses) Create(podStats *v1alpha1.PodStats) (result *v1alpha1.PodStats, err error) {
	result = &v1alpha1.PodStats{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("podstatses").
		Body(podStats).
		Do().
		Into(result)
	return
}

// Update takes the representation of a podStats and updates it. Returns the server's representation of the podStats, and an error, if there is any.
func (c *podStatses) Update(podStats *v1alpha1.PodStats) (result *v1alpha1.PodStats, err error) {
	result = &v1alpha1.PodStats{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("podstatses").
		Name(podStats.Name).
		Body(podStats).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *podStatses) UpdateStatus(podStats *v1alpha1.PodStats) (result *v1alpha1.PodStats, err error) {
	result = &v1alpha1.PodStats{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("podstatses").
		Name(podStats.Name).
		SubResource("status").
		Body(podStats).
		Do().
		Into(result)
	return
}

// Delete takes name of the podStats and deletes it. Returns an error if one occurs.
func (c *podStatses) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("podstatses").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *podStatses) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("podstatses").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched podStats.
func (c *podStatses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.PodStats, err error) {
	result = &v1alpha1.PodStats{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("podstatses").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
